/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/balcony.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/balcony.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} />
      <mesh geometry={nodes.door_right.geometry} material={materials.Material_0} />
      <mesh geometry={nodes.door_left.geometry} material={materials.Material_0} />
    </group>
  )
}

useGLTF.preload('/balcony.glb')
